version: '2.1'

services:
  node:
    image: node
    container_name: nodejs_v1
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    ports:
      - 8888:8888
      - 8081:8081
    command: "npm start"